package sample;

import javafx.geometry.Pos;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.layout.VBox;
import javafx.stage.Modality;
import javafx.stage.Stage;

/**
 * Package: sample
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 06.05.2018 2018
 */
public class ConfirmBox {
    static boolean anwwer;

    public static boolean display(String title, String message){
        Stage window = new Stage();
        Label label = new Label();
        window.initModality(Modality.APPLICATION_MODAL);
        window.setTitle(title);
        window.setMaxWidth(250);
        label.setText(message);

        // two buttons
        Button yesButton = new Button("Yes");
        Button noButton = new Button("No");
        yesButton.setOnAction(e->{
            anwwer = true;
            window.close();
        });
        noButton.setOnAction(e->{
            anwwer = false;
            window.close();
        });

        VBox layout = new VBox(10);
        layout.getChildren().addAll(label, yesButton, noButton);
        layout.setAlignment(Pos.CENTER);

        Scene scene = new Scene(layout,250,350);
        window.setScene(scene);
        window.showAndWait();

        return anwwer;
    }
}
