package sample;

/**
 * Package: sample
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 11.05.2018 2018
 */
public  class Product{
    private String name;
    private  double price;
    private int quantity;

    public void setName(String name) {
        this.name = name;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    public String getName() {
        return name;
    }

    public double getPrice() {
        return price;
    }

    public int getQuantity() {
        return quantity;
    }

    public Product(String name, double price, int quantity) {
        this.name= name;
        this.price = price;
        this.quantity = quantity;

    }
    public Product(){
    };
}
